openapi: 3.2.0
info:
  title: Stardog HTTP Stored Functions API
  description: '# Overview

    Stardog supports the standard SPARQL Protocol HTTP bindings, as well as additional functionality via HTTP.'
  contact:
    url: https://stardog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 12.0.3
  x-logo:
    url: https://d33wubrfki0l68.cloudfront.net/66e9dcff51317cfc11b9f3d4ce2917a11ba81681/543c1/img/stardog-logo-optimized.svg
servers:
- url: http://localhost:5820
tags:
- name: Stored Functions
  description: Operations relating to user-defined functions stored on the server
paths:
  /admin/functions/stored/{name}:
    get:
      tags:
      - Stored Functions
      summary: Get Stored Function
      operationId: getStoredFunction
      parameters:
      - $ref: '#/components/parameters/name_function'
      responses:
        '200':
          description: Operation successful
          content:
            text/plain:
              schema:
                type: String
              examples:
                STORED_FUNCTION:
                  description: STORED_FUNCTION
                  value: null
                  $ref: '#/components/examples/STORED_FUNCTION'
        '400':
          description: Function does not exist
        '404':
          $ref: '#/components/responses/NAME_FUNCTION_404'
    delete:
      tags:
      - Stored Functions
      summary: Delete Stored Function
      description: Delete the stored function specified in the query string parameter
      operationId: deleteStoredFunctionNamed
      parameters:
      - $ref: '#/components/parameters/name_function'
      responses:
        '204':
          description: Function deleted
        '400':
          description: Function does not exist
        '404':
          $ref: '#/components/responses/NAME_FUNCTION_404'
  /admin/functions/stored:
    get:
      tags:
      - Stored Functions
      summary: Get Stored Functions
      description: Retrieve all stored functions on the server, or optionally just the function specified in the query string parameter
      operationId: exportStoredFunctions
      parameters:
      - name: name
        in: query
        description: Stored Function name
        schema:
          type: string
      responses:
        '200':
          description: Operation successful
          content:
            text/plain:
              schema:
                type: String
              examples:
                STORED_FUNCTION:
                  description: STORED_FUNCTION
                  value: null
                  $ref: '#/components/examples/STORED_FUNCTION'
        '400':
          description: Function does not exist
        '404':
          $ref: '#/components/responses/NAME_FUNCTION_404'
    post:
      tags:
      - Stored Functions
      summary: Add Stored Function
      operationId: addStoredFunction
      requestBody:
        content:
          text/plain:
            schema:
              type: String
            examples:
              STORED_FUNCTION:
                description: STORED_FUNCTION
                value: null
                $ref: '#/components/examples/STORED_FUNCTION'
        required: true
      responses:
        '204':
          description: Function added
        '422':
          description: Function with the given name exists
    delete:
      tags:
      - Stored Functions
      summary: Delete Stored Functions
      description: Delete all stored functions on the server, or optionally just the function specified in the query string parameter
      operationId: deleteStoredFunction
      parameters:
      - name: name
        in: query
        description: Stored Function name
        schema:
          type: string
      responses:
        '204':
          description: Function deleted
        '400':
          description: Function does not exist
        '404':
          $ref: '#/components/responses/NAME_FUNCTION_404'
components:
  responses:
    NAME_FUNCTION_404:
      description: Stored function does not exist
      content:
        application/json:
          schema:
            required:
            - message
            - code
            properties:
              message:
                type: string
                example: Stored function does not exist
              code:
                type: string
                example: QEFNF2
  parameters:
    name_function:
      name: name
      in: path
      description: The name of the stored function
      required: true
      schema:
        type: string
  examples:
    STORED_FUNCTION:
      value: "FUNCTION permutation(?n,?r) {\n   (factorial(?n) / factorial((?n - ?r)))\n}"
externalDocs:
  url: https://docs.stardog.com
x-tagGroups:
- name: Data Unification
  tags:
  - Data Sources
  - Virtual Graphs
- name: Virtual Graphs External Compute
  tags:
  - Virtual Graphs External Compute
- name: Server
  tags:
  - Monitoring
  - Stored Functions
  - Server Status/Metrics
  - Server Admin
  - Queries
  - Cluster Admin
- name: Database
  tags:
  - Checkpoints
  - DB Admin
  - Integrity Constraints / SHACL
  - Data Caching
  - Graph Store Protocol
  - Matcher, aligning schemas from various data sources
  - Reasoning
  - Transactions
  - GraphQL
  - SPARQL
  - EntityResolution
- name: Security
  tags:
  - Roles
  - Permissions
  - Users
- name: Knowledge Catalog
  tags:
  - Knowledge Catalog
