openapi: 3.2.0
info:
  title: Stardog HTTP Users API
  description: '# Overview

    Stardog supports the standard SPARQL Protocol HTTP bindings, as well as additional functionality via HTTP.'
  contact:
    url: https://stardog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 12.0.3
  x-logo:
    url: https://d33wubrfki0l68.cloudfront.net/66e9dcff51317cfc11b9f3d4ce2917a11ba81681/543c1/img/stardog-logo-optimized.svg
servers:
- url: http://localhost:5820
tags:
- name: Users
  description: Operations on system users
paths:
  /admin/users:
    get:
      tags:
      - Users
      summary: List users
      operationId: listUsers
      responses:
        '200':
          $ref: '#/components/responses/USER_LIST'
    post:
      tags:
      - Users
      summary: Add user
      operationId: addUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/USER_CREATE'
      responses:
        '201':
          description: User created
        '400':
          $ref: '#/components/responses/MALFORMED_REQUEST_400'
  /admin/users/{user}/superuser:
    get:
      tags:
      - Users
      summary: User is Superuser
      description: Return whether or not a user is a Superuser
      operationId: isSuper
      parameters:
      - name: user
        $ref: '#/components/parameters/user'
      responses:
        '200':
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SUPERUSER'
        '404':
          description: User does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: User does not exist
                  code:
                    type: string
                    example: SERNF2
  /admin/users/{user}/enabled:
    get:
      tags:
      - Users
      summary: User enabled
      description: Return whether or not a user is enabled (active) in the system
      operationId: userEnabled
      parameters:
      - name: user
        $ref: '#/components/parameters/user'
      responses:
        '200':
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ENABLED'
        '404':
          description: User does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: User does not exist
                  code:
                    type: string
                    example: SERNF2
    put:
      tags:
      - Users
      summary: Enable/Disable User
      operationId: setUserEnabled
      parameters:
      - name: user
        $ref: '#/components/parameters/user'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ENABLED'
        required: true
      responses:
        '200':
          description: Flag set
        '400':
          $ref: '#/components/responses/MALFORMED_REQUEST_400'
        '404':
          description: User does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: User does not exist
                  code:
                    type: string
                    example: SERNF2
  /admin/users/{user}/pwd:
    put:
      tags:
      - Users
      summary: Change user's password
      operationId: changePassword
      parameters:
      - name: user
        $ref: '#/components/parameters/user'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/USER_PASSWD'
        required: true
      responses:
        '200':
          description: Password successfully changed
        '400':
          $ref: '#/components/responses/MALFORMED_REQUEST_400'
        '404':
          description: User does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: User does not exist
                  code:
                    type: string
                    example: SERNF2
  /admin/users/{user}/roles:
    get:
      tags:
      - Users
      summary: Get user's roles
      description: Retrieve a list of all roles explicitly assigned to a user
      operationId: getUserRoles
      parameters:
      - name: user
        $ref: '#/components/parameters/user'
      responses:
        '200':
          $ref: '#/components/responses/ROLE_LIST'
        '404':
          description: User does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: User does not exist
                  code:
                    type: string
                    example: SERNF2
    put:
      tags:
      - Users
      summary: Set user's roles
      description: Overwrite the list of roles explicitly assigned to a user
      operationId: setUserRoles
      parameters:
      - name: user
        $ref: '#/components/parameters/user'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ROLE_LIST'
        required: true
      responses:
        '200':
          description: Roles successfully updated
        '400':
          $ref: '#/components/responses/MALFORMED_REQUEST_400'
        '404':
          description: User does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: User does not exist
                  code:
                    type: string
                    example: SERNF2
    post:
      tags:
      - Users
      summary: Add role to user
      operationId: addUserRole
      parameters:
      - name: user
        $ref: '#/components/parameters/user'
      requestBody:
        $ref: '#/components/requestBodies/ROLENAME'
      responses:
        '204':
          description: Role successfully added
        '400':
          $ref: '#/components/responses/MALFORMED_REQUEST_400'
        '404':
          description: User does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: User does not exist
                  code:
                    type: string
                    example: SERNF2
  /admin/users/{user}/roles/{role}:
    delete:
      tags:
      - Users
      summary: Remove role from user
      operationId: removeUserRole
      parameters:
      - name: user
        $ref: '#/components/parameters/user'
      - name: role
        $ref: '#/components/parameters/role'
      responses:
        '204':
          description: Role successfully removed
        '404':
          description: User/Role does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: User does not exist
                  code:
                    type: string
                    example: SERNF2
  /admin/users/{user}/auto_created:
    get:
      tags:
      - Users
      summary: User auto-created
      description: Return whether a user was auto-created as a result the OAuth jwt authentication process
      operationId: userAutoCreated
      parameters:
      - name: user
        $ref: '#/components/parameters/user'
      responses:
        '200':
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AUTO_CREATED'
        '404':
          description: User does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: User does not exist
                  code:
                    type: string
                    example: SERNF2
  /admin/users/list:
    get:
      tags:
      - Users
      summary: List users with attributes, roles and permissions
      description: Retrieve a detailed list of all users, including their roles, permissions, and status
      operationId: listUsersDetailed
      responses:
        '200':
          $ref: '#/components/responses/USER_LIST_DETAILED'
  /admin/users/{user}:
    get:
      tags:
      - Users
      summary: Get User
      description: Retrieve attributes, roles, and permissions of a User
      operationId: getUser
      parameters:
      - name: user
        $ref: '#/components/parameters/user'
      responses:
        '200':
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/USER'
        '404':
          description: User does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: User does not exist
                  code:
                    type: string
                    example: SERNF2
    delete:
      tags:
      - Users
      summary: Delete User
      operationId: deleteUser
      parameters:
      - name: user
        $ref: '#/components/parameters/user'
      responses:
        '204':
          description: User deleted
        '404':
          description: User does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: User does not exist
                  code:
                    type: string
                    example: SERNF2
components:
  schemas:
    USER_PASSWD:
      required:
      - password
      properties:
        password:
          type: string
    USER_LIST_DETAILED:
      type: array
      items:
        required:
        - username
        - enabled
        - superuser
        - roles
        - permissions
        properties:
          username:
            type: string
          enabled:
            type: boolean
          superuser:
            type: boolean
          roles:
            type: array
            items:
              type: string
          permissions:
            type: array
            items:
              $ref: '#/components/schemas/PERMISSION_WITH_EXPLICIT'
    PERMISSION_WITH_EXPLICIT:
      required:
      - action
      - resource_type
      - resource
      properties:
        action:
          type: string
          enum:
          - read
          - write
          - create
          - delete
          - revoke
          - grant
          - execute
          - all
        resource_type:
          type: string
          enum:
          - ALL
          - USER
          - ROLE
          - ROLE_ASSIGNMENT
          - PERMISSION
          - DATABASE
          - DATABASE_EXPORT
          - NAMED_GRAPH
          - DATA_SOURCE
          - VIRTUAL_GRAPH
          - DBMS_ADMIN
          - DATABASE_METADATA
          - DATABASE_ADMIN
          - DATABASE_MODELING
          - STORED_QUERY
          - CACHE
          - CACHE_TARGET
          - SENSITIVE_PROPERTIES
          - ENTITY_RESOLUTION
        resource:
          type: array
          items:
            type: string
        explicit:
          type: boolean
          description: Whether this permission is explicitly granted to the user versus granted via a role
    GENERIC_RESPONSE_ERROR_MESSAGE:
      required:
      - message
      properties:
        message:
          type: string
          example: Unexpected end of file [L9]
        code:
          type: string
          example: QEIVR2
    SUPERUSER:
      required:
      - superuser
      properties:
        superuser:
          type: boolean
    AUTO_CREATED:
      required:
      - auto_created
      properties:
        auto_created:
          type: boolean
    ROLENAME:
      required:
      - rolename
      properties:
        rolename:
          type: string
    USER_LIST:
      required:
      - users
      properties:
        users:
          type: array
          items:
            type: string
    USER:
      required:
      - enabled
      - superuser
      - roles
      - permissions
      properties:
        enabled:
          type: boolean
        superuser:
          type: boolean
        roles:
          type: array
          items:
            type: string
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/PERMISSION_WITH_EXPLICIT'
    USER_CREATE:
      required:
      - username
      - password
      properties:
        username:
          type: string
        password:
          type: array
          description: Array of chars
          items:
            maxLength: 1
            minLength: 1
            type: string
    ENABLED:
      required:
      - enabled
      properties:
        enabled:
          type: boolean
    ROLE_LIST:
      required:
      - roles
      properties:
        roles:
          type: array
          items:
            type: string
  responses:
    MALFORMED_REQUEST_400:
      description: Malformed request body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GENERIC_RESPONSE_ERROR_MESSAGE'
    USER_LIST_DETAILED:
      description: List of Users in system, including their roles, permissions, and status
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/USER_LIST_DETAILED'
    USER_LIST:
      description: List of Users in system
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/USER_LIST'
    ROLE_LIST:
      description: List of Roles in system
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ROLE_LIST'
  parameters:
    role:
      name: role
      in: path
      description: Role name
      required: true
      schema:
        type: string
    user:
      name: user
      in: path
      description: Username
      required: true
      schema:
        type: string
  requestBodies:
    ROLENAME:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ROLENAME'
externalDocs:
  url: https://docs.stardog.com
x-tagGroups:
- name: Data Unification
  tags:
  - Data Sources
  - Virtual Graphs
- name: Virtual Graphs External Compute
  tags:
  - Virtual Graphs External Compute
- name: Server
  tags:
  - Monitoring
  - Stored Functions
  - Server Status/Metrics
  - Server Admin
  - Queries
  - Cluster Admin
- name: Database
  tags:
  - Checkpoints
  - DB Admin
  - Integrity Constraints / SHACL
  - Data Caching
  - Graph Store Protocol
  - Matcher, aligning schemas from various data sources
  - Reasoning
  - Transactions
  - GraphQL
  - SPARQL
  - EntityResolution
- name: Security
  tags:
  - Roles
  - Permissions
  - Users
- name: Knowledge Catalog
  tags:
  - Knowledge Catalog
