openapi: 3.2.0
info:
  title: Stardog HTTP Checkpoints API
  description: '# Overview

    Stardog supports the standard SPARQL Protocol HTTP bindings, as well as additional functionality via HTTP.'
  contact:
    url: https://stardog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 12.0.3
  x-logo:
    url: https://d33wubrfki0l68.cloudfront.net/66e9dcff51317cfc11b9f3d4ce2917a11ba81681/543c1/img/stardog-logo-optimized.svg
servers:
- url: http://localhost:5820
tags:
- name: Checkpoints
  description: Operations for database checkpoints
paths:
  /admin/checkpoint/{db}/{checkpoint}:
    put:
      tags:
      - Checkpoints
      summary: Restore checkpoints
      operationId: restoreCheckpoint
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      - name: checkpoint
        in: path
        description: the name of the checkpoint
        required: true
        schema:
          type: string
      responses:
        '200':
          $ref: '#/components/responses/CHECKPOINT_RESTORE'
        '400':
          $ref: '#/components/responses/MALFORMED_REQUEST_400'
        '404':
          description: Database does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
  /admin/checkpoint/{db}:
    get:
      tags:
      - Checkpoints
      summary: List checkpoints
      operationId: listCheckpoints
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      responses:
        '200':
          $ref: '#/components/responses/CHECKPOINT_LIST'
        '404':
          description: Database does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
    post:
      tags:
      - Checkpoints
      summary: Create checkpoint
      operationId: createCheckpoint
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      responses:
        '200':
          $ref: '#/components/responses/CHECKPOINT_CREATE'
        '400':
          $ref: '#/components/responses/MALFORMED_REQUEST_400'
        '404':
          description: Database does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
components:
  responses:
    CHECKPOINT_RESTORE:
      description: Checkpoint Restore
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CHECKPOINT_RESTORE'
    CHECKPOINT_CREATE:
      description: Checkpoint Create
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CHECKPOINT_CREATE'
    CHECKPOINT_LIST:
      description: Checkpoint List
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CHECKPOINT_LIST'
    MALFORMED_REQUEST_400:
      description: Malformed request body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GENERIC_RESPONSE_ERROR_MESSAGE'
  schemas:
    GENERIC_RESPONSE_ERROR_MESSAGE:
      required:
      - message
      properties:
        message:
          type: string
          example: Unexpected end of file [L9]
        code:
          type: string
          example: QEIVR2
    CHECKPOINT_CREATE:
      properties:
        description:
          type: string
          example: Prior to 8.0.2 upgrade
    CHECKPOINT_RESTORE:
      properties:
        checkpoint:
          type: string
          example: system_2021-05-14_04.56
    CHECKPOINT_LIST:
      properties:
        checkpoints:
          type: array
          items:
            properties:
              checkpoint:
                type: string
                example: system_2021-05-14_02.34
              description:
                type: string
                example: Prior to 8.0.1 upgrade
  parameters:
    db:
      name: db
      in: path
      description: Database name
      required: true
      schema:
        type: string
      example: myDb
externalDocs:
  url: https://docs.stardog.com
x-tagGroups:
- name: Data Unification
  tags:
  - Data Sources
  - Virtual Graphs
- name: Virtual Graphs External Compute
  tags:
  - Virtual Graphs External Compute
- name: Server
  tags:
  - Monitoring
  - Stored Functions
  - Server Status/Metrics
  - Server Admin
  - Queries
  - Cluster Admin
- name: Database
  tags:
  - Checkpoints
  - DB Admin
  - Integrity Constraints / SHACL
  - Data Caching
  - Graph Store Protocol
  - Matcher, aligning schemas from various data sources
  - Reasoning
  - Transactions
  - GraphQL
  - SPARQL
  - EntityResolution
- name: Security
  tags:
  - Roles
  - Permissions
  - Users
- name: Knowledge Catalog
  tags:
  - Knowledge Catalog
