openapi: 3.2.0
info:
  title: Stardog HTTP Roles API
  description: '# Overview

    Stardog supports the standard SPARQL Protocol HTTP bindings, as well as additional functionality via HTTP.'
  contact:
    url: https://stardog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 12.0.3
  x-logo:
    url: https://d33wubrfki0l68.cloudfront.net/66e9dcff51317cfc11b9f3d4ce2917a11ba81681/543c1/img/stardog-logo-optimized.svg
servers:
- url: http://localhost:5820
tags:
- name: Roles
  description: Operations on system roles
paths:
  /admin/roles:
    get:
      tags:
      - Roles
      summary: List Roles
      description: Get the names of all roles in the system
      operationId: listRoles
      responses:
        '200':
          $ref: '#/components/responses/ROLE_LIST'
    post:
      tags:
      - Roles
      summary: Add role
      operationId: addRole
      requestBody:
        $ref: '#/components/requestBodies/ROLENAME'
      responses:
        '201':
          description: Role added
        '400':
          $ref: '#/components/responses/MALFORMED_REQUEST_400'
  /admin/roles/{role}:
    delete:
      tags:
      - Roles
      summary: Delete role
      operationId: deleteRole
      parameters:
      - name: role
        $ref: '#/components/parameters/role'
      - name: force
        in: query
        description: Whether to force delete if role is assigned to users
        schema:
          type: boolean
      responses:
        '204':
          description: Role deleted
        '404':
          description: Role does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Role does not exist
                  code:
                    type: string
                    example: SERNF2
  /admin/roles/{role}/users:
    get:
      tags:
      - Roles
      summary: Get users with role
      description: Returns a list of all users that have a specific role
      operationId: getUsersWithRole
      parameters:
      - name: role
        $ref: '#/components/parameters/role'
      responses:
        '200':
          $ref: '#/components/responses/USER_LIST'
        '404':
          description: Role does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Role does not exist
                  code:
                    type: string
                    example: SERNF2
  /admin/roles/list:
    get:
      tags:
      - Roles
      summary: List Roles with their permissions
      description: Retrieve a detailed list of all roles, including their permissions
      operationId: listRolesDetailed
      responses:
        '200':
          $ref: '#/components/responses/ROLE_LIST_DETAILED'
components:
  schemas:
    USER_LIST:
      required:
      - users
      properties:
        users:
          type: array
          items:
            type: string
    PERMISSION_WITH_EXPLICIT:
      required:
      - action
      - resource_type
      - resource
      properties:
        action:
          type: string
          enum:
          - read
          - write
          - create
          - delete
          - revoke
          - grant
          - execute
          - all
        resource_type:
          type: string
          enum:
          - ALL
          - USER
          - ROLE
          - ROLE_ASSIGNMENT
          - PERMISSION
          - DATABASE
          - DATABASE_EXPORT
          - NAMED_GRAPH
          - DATA_SOURCE
          - VIRTUAL_GRAPH
          - DBMS_ADMIN
          - DATABASE_METADATA
          - DATABASE_ADMIN
          - DATABASE_MODELING
          - STORED_QUERY
          - CACHE
          - CACHE_TARGET
          - SENSITIVE_PROPERTIES
          - ENTITY_RESOLUTION
        resource:
          type: array
          items:
            type: string
        explicit:
          type: boolean
          description: Whether this permission is explicitly granted to the user versus granted via a role
    GENERIC_RESPONSE_ERROR_MESSAGE:
      required:
      - message
      properties:
        message:
          type: string
          example: Unexpected end of file [L9]
        code:
          type: string
          example: QEIVR2
    ROLE_LIST_DETAILED:
      type: array
      items:
        required:
        - rolename
        - permissions
        properties:
          rolename:
            type: string
          permissions:
            type: array
            items:
              $ref: '#/components/schemas/PERMISSION_WITH_EXPLICIT'
    ROLENAME:
      required:
      - rolename
      properties:
        rolename:
          type: string
    ROLE_LIST:
      required:
      - roles
      properties:
        roles:
          type: array
          items:
            type: string
  parameters:
    role:
      name: role
      in: path
      description: Role name
      required: true
      schema:
        type: string
  responses:
    ROLE_LIST_DETAILED:
      description: List of Roles in system, including their permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ROLE_LIST_DETAILED'
    MALFORMED_REQUEST_400:
      description: Malformed request body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GENERIC_RESPONSE_ERROR_MESSAGE'
    USER_LIST:
      description: List of Users in system
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/USER_LIST'
    ROLE_LIST:
      description: List of Roles in system
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ROLE_LIST'
  requestBodies:
    ROLENAME:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ROLENAME'
externalDocs:
  url: https://docs.stardog.com
x-tagGroups:
- name: Data Unification
  tags:
  - Data Sources
  - Virtual Graphs
- name: Virtual Graphs External Compute
  tags:
  - Virtual Graphs External Compute
- name: Server
  tags:
  - Monitoring
  - Stored Functions
  - Server Status/Metrics
  - Server Admin
  - Queries
  - Cluster Admin
- name: Database
  tags:
  - Checkpoints
  - DB Admin
  - Integrity Constraints / SHACL
  - Data Caching
  - Graph Store Protocol
  - Matcher, aligning schemas from various data sources
  - Reasoning
  - Transactions
  - GraphQL
  - SPARQL
  - EntityResolution
- name: Security
  tags:
  - Roles
  - Permissions
  - Users
- name: Knowledge Catalog
  tags:
  - Knowledge Catalog
