openapi: 3.2.0
info:
  title: Stardog HTTP Transactions API
  description: '# Overview

    Stardog supports the standard SPARQL Protocol HTTP bindings, as well as additional functionality via HTTP.'
  contact:
    url: https://stardog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 12.0.3
  x-logo:
    url: https://d33wubrfki0l68.cloudfront.net/66e9dcff51317cfc11b9f3d4ce2917a11ba81681/543c1/img/stardog-logo-optimized.svg
servers:
- url: http://localhost:5820
tags:
- name: Transactions
  description: Transactional operations
paths:
  /{db}/transaction/begin:
    post:
      tags:
      - Transactions
      summary: Begin a transaction
      operationId: beginTransaction
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      responses:
        '200':
          description: Operation successful
          content:
            text/plain:
              example: 067e6162-3b6f-4ae2-a171-2470b63dff00
        '404':
          description: Database does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
      x-sort-order:
        group: '1'
        order: '1'
  /{db}/transaction/begin/{txid}:
    post:
      tags:
      - Transactions
      summary: Begin a transaction with specified txid
      operationId: beginTx
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      - name: txid
        $ref: '#/components/parameters/txid'
      responses:
        '200':
          description: Transaction begun
          content:
            text/plain:
              example: 067e6162-3b6f-4ae2-a171-2470b63dff00
        '404':
          description: Database/Transaction does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
      x-sort-order:
        group: '1'
        order: '2'
  /{db}/transaction/commit/{txid}:
    post:
      tags:
      - Transactions
      summary: Commit a transaction
      operationId: commitTransaction
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      - name: txid
        $ref: '#/components/parameters/txid'
      responses:
        '200':
          description: Commit successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/COMMIT_RESULT'
        '404':
          description: Database/Transaction does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
      x-sort-order:
        group: '1'
        order: '3'
  /{db}/transaction/rollback/{txid}:
    post:
      tags:
      - Transactions
      summary: Rollback a transaction
      operationId: rollbackTransaction
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      - name: txid
        $ref: '#/components/parameters/txid'
      responses:
        '200':
          $ref: '#/components/responses/EMPTY_SUCCESS'
        '404':
          description: Database/Transaction does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
      x-sort-order:
        group: '1'
        order: '4'
  /{db}/{txid}/clear:
    post:
      tags:
      - Transactions
      summary: Clear database within a transaction
      operationId: clearDatabasesInTx
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      - name: txid
        $ref: '#/components/parameters/txid'
      - $ref: '#/components/parameters/graph-uri'
      responses:
        '200':
          $ref: '#/components/responses/EMPTY_SUCCESS'
        '404':
          description: Database/Transaction does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
  /{db}/{txid}/remove:
    post:
      tags:
      - Transactions
      summary: Remove data within a transaction
      operationId: removeDataInTx
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      - name: txid
        $ref: '#/components/parameters/txid'
      - $ref: '#/components/parameters/graph-uri'
      requestBody:
        content:
          text/turtle:
            schema:
              type: String
            examples:
              GENERIC_TURTLE:
                description: GENERIC_TURTLE
                value: null
                $ref: '#/components/examples/GENERIC_TURTLE'
          application/trig:
            schema:
              type: String
            examples:
              GENERIC_TRIG:
                description: GENERIC_TRIG
                value: null
                $ref: '#/components/examples/GENERIC_TRIG'
          application/rdf+xml:
            schema:
              type: String
            examples:
              GENERIC_RDFXML:
                description: GENERIC_RDFXML
                value: null
                $ref: '#/components/examples/GENERIC_RDFXML'
          application/n-triples:
            schema:
              type: String
            examples:
              GENERIC_NTRIPLES:
                description: GENERIC_NTRIPLES
                value: null
                $ref: '#/components/examples/GENERIC_NTRIPLES'
          application/n-quads:
            schema:
              type: String
            examples:
              GENERIC_NQUADS:
                description: GENERIC_NQUADS
                value: null
                $ref: '#/components/examples/GENERIC_NQUADS'
          application/ld+json:
            schema:
              $ref: '#/components/schemas/GENERIC_JSONLD'
        required: true
      responses:
        '200':
          $ref: '#/components/responses/EMPTY_SUCCESS'
        '404':
          description: Database/Transaction does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
  /{db}/{txid}/add:
    post:
      tags:
      - Transactions
      summary: Add data within a transaction
      operationId: addDataInTx
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      - name: txid
        $ref: '#/components/parameters/txid'
      - $ref: '#/components/parameters/graph-uri'
      - $ref: '#/components/parameters/header_content_encoding'
      requestBody:
        content:
          text/turtle:
            schema:
              type: String
            examples:
              GENERIC_TURTLE:
                description: GENERIC_TURTLE
                value: null
                $ref: '#/components/examples/GENERIC_TURTLE'
          application/trig:
            schema:
              type: String
            examples:
              GENERIC_TRIG:
                description: GENERIC_TRIG
                value: null
                $ref: '#/components/examples/GENERIC_TRIG'
          application/rdf+xml:
            schema:
              type: String
            examples:
              GENERIC_RDFXML:
                description: GENERIC_RDFXML
                value: null
                $ref: '#/components/examples/GENERIC_RDFXML'
          application/n-triples:
            schema:
              type: String
            examples:
              GENERIC_NTRIPLES:
                description: GENERIC_NTRIPLES
                value: null
                $ref: '#/components/examples/GENERIC_NTRIPLES'
          application/n-quads:
            schema:
              type: String
            examples:
              GENERIC_NQUADS:
                description: GENERIC_NQUADS
                value: null
                $ref: '#/components/examples/GENERIC_NQUADS'
          application/ld+json:
            schema:
              $ref: '#/components/schemas/GENERIC_JSONLD'
        required: true
      responses:
        '200':
          $ref: '#/components/responses/EMPTY_SUCCESS'
        '404':
          description: Database/Transaction does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
  /{db}/transaction:
    get:
      tags:
      - Transactions
      summary: List all open transactions on a database
      operationId: listTransactions
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      responses:
        '200':
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TRANSACTION'
        '404':
          description: Database does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
components:
  parameters:
    txid:
      name: txid
      in: path
      description: Transaction ID
      required: true
      schema:
        type: string
        format: uuid
        example: 4ea1ebac-48f0-459c-a9a7-6cad7189403d
    db:
      name: db
      in: path
      description: Database name
      required: true
      schema:
        type: string
      example: myDb
    graph-uri:
      name: graph-uri
      in: query
      description: Named Graph / Context
      required: false
      schema:
        type: string
        format: URI
      example: https://stardog.com/graphs/myGraph
    header_content_encoding:
      name: Content-Encoding
      in: header
      description: Allowable encodings for request body
      schema:
        type: string
        enum:
        - NONE
        - GZIP
        - BZIP2
        - ZIP
  schemas:
    COMMIT_RESULT:
      required:
      - added
      - removed
      properties:
        added:
          type: integer
          description: Approximate number of triples added
          format: int32
          example: 42
        removed:
          type: integer
          description: Approximate number of triples removed
          format: int32
          example: 29
    GENERIC_JSONLD:
      properties:
        '@id':
          type: string
          example: urn:example:Entity1
        '@type':
          type: string
          example: urn:example:Entity
        urn:example:hasProp:
          required:
          - '@id'
          type: array
          items:
            required:
            - '@value'
            properties:
              '@type':
                type: string
                example: http://www.w3.org/2001/XMLSchema#integer
              '@value':
                type: string
                example: '42'
    TRANSACTION:
      required:
      - transactions
      properties:
        transactions:
          type: array
          items:
            required:
            - id
            - db
            - user
            - startTime
            properties:
              id:
                type: string
                format: uuid
                example: 4ea1ebac-48f0-459c-a9a7-6cad7189403d
              db:
                type: string
                example: myDb
              user:
                type: string
                example: admin
              startTime:
                type: integer
                description: Unix timestamp when transaction started
                format: int64
                example: 1579812754096
              status:
                type: string
                example: IDLE
  examples:
    GENERIC_TRIG:
      value: "@prefix : <urn:example:> .\n@prefix owl: <http://www.w3.org/2002/07/owl#> .\n@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n@prefix stardog: <tag:stardog:api:> .\n@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n\n{ \t<urn:example:Entity1> a <urn:example:Entity> ;\n\t\t <urn:example:hasProp> 42 .\n}"
    GENERIC_NQUADS:
      value: '<urn:context> <urn:example:Entity1> a <urn:example:Entity> .

        <urn:context> <urn:example:Entity1> <urn:example:hasProp> 42 .'
    GENERIC_TURTLE:
      value: "@prefix : <urn:example:> .\n@prefix owl: <http://www.w3.org/2002/07/owl#> .\n@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n@prefix stardog: <tag:stardog:api:> .\n@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n\n<urn:example:Entity1> a <urn:example:Entity> ;\n\t<urn:example:hasProp> 42 ."
    GENERIC_NTRIPLES:
      value: '<urn:example:Entity1> a <urn:example:Entity> .

        <urn:example:Entity1> <urn:example:hasProp> 42 .'
    GENERIC_RDFXML:
      value: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<rdf:RDF\n\txmlns=\"http://api.stardog.com/\"\n\txmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n\txmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n\txmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n\txmlns:stardog=\"tag:stardog:api:\"\n\txmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\">\n\n<rdf:Description rdf:about=\"urn:example:Entity1\">\n\t<rdf:type rdf:resource=\"urn:example:Entity\"/>\n\t<hasProp xmlns=\"urn:example:\" rdf:datatype=\"http://www.w3.org/2001/XMLSchema#integer\">42</hasProp>\n</rdf:Description>\n\n</rdf:RDF>"
  responses:
    EMPTY_SUCCESS:
      description: Operation successful
externalDocs:
  url: https://docs.stardog.com
x-tagGroups:
- name: Data Unification
  tags:
  - Data Sources
  - Virtual Graphs
- name: Virtual Graphs External Compute
  tags:
  - Virtual Graphs External Compute
- name: Server
  tags:
  - Monitoring
  - Stored Functions
  - Server Status/Metrics
  - Server Admin
  - Queries
  - Cluster Admin
- name: Database
  tags:
  - Checkpoints
  - DB Admin
  - Integrity Constraints / SHACL
  - Data Caching
  - Graph Store Protocol
  - Matcher, aligning schemas from various data sources
  - Reasoning
  - Transactions
  - GraphQL
  - SPARQL
  - EntityResolution
- name: Security
  tags:
  - Roles
  - Permissions
  - Users
- name: Knowledge Catalog
  tags:
  - Knowledge Catalog
