openapi: 3.2.0
info:
  title: Stardog HTTP Matcher, aligning schemas from various data…
  description: '# Overview

    Stardog supports the standard SPARQL Protocol HTTP bindings, as well as additional functionality via HTTP.'
  contact:
    url: https://stardog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 12.0.3
  x-logo:
    url: https://d33wubrfki0l68.cloudfront.net/66e9dcff51317cfc11b9f3d4ce2917a11ba81681/543c1/img/stardog-logo-optimized.svg
servers:
- url: http://localhost:5820
tags:
- name: Matcher, aligning schemas from various data sources
  description: ''
paths:
  /matcher/suggestions:
    post:
      tags:
      - Matcher, aligning schemas from various data sources
      summary: Aligns the source and target data source schemas
      operationId: createTypeAlignments
      responses:
        '200':
          description: aligned data source schemas
          content:
            text/turtle: {}
            application/trig: {}
            application/rdf+xml: {}
            application/n-triples: {}
            application/n-quads: {}
            application/ld+json:
              schema:
                $ref: '#/components/schemas/GENERIC_JSON_OBJECT'
            application/json:
              schema:
                $ref: '#/components/schemas/GENERIC_JSON_OBJECT'
components:
  schemas:
    GENERIC_JSON_OBJECT:
      type: object
      additionalProperties:
        type: string
externalDocs:
  url: https://docs.stardog.com
x-tagGroups:
- name: Data Unification
  tags:
  - Data Sources
  - Virtual Graphs
- name: Virtual Graphs External Compute
  tags:
  - Virtual Graphs External Compute
- name: Server
  tags:
  - Monitoring
  - Stored Functions
  - Server Status/Metrics
  - Server Admin
  - Queries
  - Cluster Admin
- name: Database
  tags:
  - Checkpoints
  - DB Admin
  - Integrity Constraints / SHACL
  - Data Caching
  - Graph Store Protocol
  - Matcher, aligning schemas from various data sources
  - Reasoning
  - Transactions
  - GraphQL
  - SPARQL
  - EntityResolution
- name: Security
  tags:
  - Roles
  - Permissions
  - Users
- name: Knowledge Catalog
  tags:
  - Knowledge Catalog
