openapi: 3.2.0
info:
  title: Stardog HTTP Graph QL API
  description: '# Overview

    Stardog supports the standard SPARQL Protocol HTTP bindings, as well as additional functionality via HTTP.'
  contact:
    url: https://stardog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 12.0.3
  x-logo:
    url: https://d33wubrfki0l68.cloudfront.net/66e9dcff51317cfc11b9f3d4ce2917a11ba81681/543c1/img/stardog-logo-optimized.svg
servers:
- url: http://localhost:5820
tags:
- name: Graph QL
  description: GraphQL Queries
paths:
  /{db}/graphql/schemas:
    get:
      tags:
      - Graph QL
      summary: List schemas
      operationId: listGraphQLSchemas
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      responses:
        '200':
          description: List of schemas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GRAPHQL_SCHEMAS'
        '404':
          description: Database does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
    delete:
      tags:
      - Graph QL
      summary: Clear schemas
      operationId: clearGraphQLSchemas
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      responses:
        '204':
          description: Schemas cleared
        '404':
          description: Database does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
  /{db}/graphql/{schema}:
    get:
      tags:
      - Graph QL
      summary: Perform GraphQL query with schema
      operationId: graphQLQueryGetWithSchema
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      - name: schema
        $ref: '#/components/parameters/schema'
      - name: query
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/GRAPHQL_QUERY'
      - $ref: '#/components/parameters/name_schema'
      responses:
        '200':
          $ref: '#/components/responses/GRAPHQL_QUERY_RESULT'
        '404':
          description: Database/Schema does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
    post:
      tags:
      - Graph QL
      summary: Perform GraphQL query with schema
      operationId: graphQLQueryPostWithSchema
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      - name: schema
        $ref: '#/components/parameters/schema'
      - $ref: '#/components/parameters/name_schema'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GRAPHQL_QUERY_POST'
        required: true
      responses:
        '200':
          $ref: '#/components/responses/GRAPHQL_QUERY_RESULT'
        '404':
          description: Database/Schema does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
  /{db}/graphql:
    get:
      tags:
      - Graph QL
      summary: Perform GraphQL query
      operationId: graphQLQueryGet
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      - name: query
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/GRAPHQL_QUERY'
      responses:
        '200':
          $ref: '#/components/responses/GRAPHQL_QUERY_RESULT'
        '404':
          description: Database does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
    post:
      tags:
      - Graph QL
      summary: Perform GraphQL query
      operationId: graphQLQueryPost
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GRAPHQL_QUERY_POST'
        required: true
      responses:
        '200':
          $ref: '#/components/responses/GRAPHQL_QUERY_RESULT'
        '404':
          description: Database does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
  /{db}/graphql/schemas/{schema}:
    get:
      tags:
      - Graph QL
      summary: Get schema
      operationId: getGraphQLSchema
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      - name: schema
        $ref: '#/components/parameters/schema'
      - $ref: '#/components/parameters/name_schema'
      responses:
        '200':
          description: Operation successful
          content:
            application/graphql:
              examples:
                GRAPHQL_SCHEMA:
                  description: GRAPHQL_SCHEMA
                  value: null
                  $ref: '#/components/examples/GRAPHQL_SCHEMA'
        '404':
          description: Database/Schema does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
    put:
      tags:
      - Graph QL
      summary: Update schema
      operationId: updateGraphQLSchema
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      - name: schema
        $ref: '#/components/parameters/schema'
      - $ref: '#/components/parameters/name_schema'
      requestBody:
        $ref: '#/components/requestBodies/GRAPHQL_SCHEMA'
      responses:
        '200':
          description: Schema updated
        '404':
          description: Database/Schema does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
    post:
      tags:
      - Graph QL
      summary: Add schema
      operationId: addGraphQLSchema
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      - name: schema
        $ref: '#/components/parameters/schema'
      - $ref: '#/components/parameters/name_schema'
      requestBody:
        $ref: '#/components/requestBodies/GRAPHQL_SCHEMA'
      responses:
        '201':
          description: Schema added
        '404':
          description: Database/Schema does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
    delete:
      tags:
      - Graph QL
      summary: Remove schema
      operationId: removeGraphQLSchema
      parameters:
      - name: db
        $ref: '#/components/parameters/db'
      - name: schema
        $ref: '#/components/parameters/schema'
      - $ref: '#/components/parameters/name_schema'
      responses:
        '204':
          description: Schema removed
        '404':
          description: Database/Schema does not exist
          content:
            application/json:
              schema:
                required:
                - message
                - code
                properties:
                  message:
                    type: string
                    example: Database does not exist
                  code:
                    type: string
                    example: 0D0DU2
components:
  schemas:
    GRAPHQL_SCHEMAS:
      required:
      - schemas
      properties:
        schemas:
          type: array
          items:
            type: string
    GRAPHQL_QUERY:
      type: string
      example: '{ Human { name } }'
    GRAPHQL_QUERY_RESULT:
      required:
      - data
      properties:
        data:
          type: array
          items:
            type: object
            additionalProperties:
              type: string
    GRAPHQL_QUERY_POST:
      required:
      - query
      properties:
        query:
          $ref: '#/components/schemas/GRAPHQL_QUERY'
        operationName:
          type: string
        variables:
          type: object
  parameters:
    name_schema:
      name: schema
      in: path
      description: The name of the schema
      required: true
      schema:
        type: string
    schema:
      name: schema
      in: query
      description: The name of the schema
      schema:
        type: string
    db:
      name: db
      in: path
      description: Database name
      required: true
      schema:
        type: string
      example: myDb
  requestBodies:
    GRAPHQL_SCHEMA:
      content:
        application/graphql:
          schema:
            type: string
          examples:
            GRAPHQL_SCHEMA:
              value: null
              $ref: '#/components/examples/GRAPHQL_SCHEMA'
  responses:
    GRAPHQL_QUERY_RESULT:
      description: Result of GraphQL query
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GRAPHQL_QUERY_RESULT'
  examples:
    GRAPHQL_SCHEMA:
      value: "type Author {\n  id: Int!\n  firstName: String\n  lastName: String\n  posts: [Post]\n}type Post {\n  id: Int!\n  title: String\n  author: Author\n  votes: Int\n}type Query {\n  posts: [Post]\n  author(id: Int!): Author\n}\n"
externalDocs:
  url: https://docs.stardog.com
x-tagGroups:
- name: Data Unification
  tags:
  - Data Sources
  - Virtual Graphs
- name: Virtual Graphs External Compute
  tags:
  - Virtual Graphs External Compute
- name: Server
  tags:
  - Monitoring
  - Stored Functions
  - Server Status/Metrics
  - Server Admin
  - Queries
  - Cluster Admin
- name: Database
  tags:
  - Checkpoints
  - DB Admin
  - Integrity Constraints / SHACL
  - Data Caching
  - Graph Store Protocol
  - Matcher, aligning schemas from various data sources
  - Reasoning
  - Transactions
  - GraphQL
  - SPARQL
  - EntityResolution
- name: Security
  tags:
  - Roles
  - Permissions
  - Users
- name: Knowledge Catalog
  tags:
  - Knowledge Catalog
