openapi: 3.2.0
info:
  title: Stardog HTTP Server Status/Metrics API
  description: '# Overview

    Stardog supports the standard SPARQL Protocol HTTP bindings, as well as additional functionality via HTTP.'
  contact:
    url: https://stardog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 12.0.3
  x-logo:
    url: https://d33wubrfki0l68.cloudfront.net/66e9dcff51317cfc11b9f3d4ce2917a11ba81681/543c1/img/stardog-logo-optimized.svg
servers:
- url: http://localhost:5820
tags:
- name: Server Status/Metrics
  description: ''
paths:
  /admin/status:
    get:
      tags:
      - Server Status/Metrics
      summary: Get Server/Database metrics
      description: Return metric information from the registry in JSON format. If 'admin' is replaced in the path with a valid database name, metrics for just that database will be returned.
      operationId: status
      responses:
        '200':
          description: Server/Database metrics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GENERIC_JSON_OBJECT'
  /admin/status/prometheus:
    get:
      tags:
      - Server Status/Metrics
      summary: Get Prometheus metrics
      description: Return metric information from the registry in Prometheus format
      operationId: prometheus
      parameters:
      - name: include
        in: query
        description: Regex used to match metric names to be included
        schema:
          type: string
      - name: exclude
        in: query
        description: Regex used to match metric names to be excluded, takes precedence over include
        schema:
          type: string
      responses:
        '200':
          description: Prometheus metrics
          content:
            text/plain: {}
  /admin/status/prometheus/internal:
    get:
      tags:
      - Server Status/Metrics
      summary: Get Prometheus metrics (only accessible from a restricted cidr range)
      description: Return metric information from the registry in Prometheus format
      operationId: prometheusInternal
      parameters:
      - name: include
        in: query
        description: Regex used to match metric names to be included
        schema:
          type: string
      - name: exclude
        in: query
        description: Regex used to match metric names to be excluded, takes precedence over include
        schema:
          type: string
      responses:
        '200':
          description: Prometheus metrics
          content:
            text/plain: {}
components:
  schemas:
    GENERIC_JSON_OBJECT:
      type: object
      additionalProperties:
        type: string
externalDocs:
  url: https://docs.stardog.com
x-tagGroups:
- name: Data Unification
  tags:
  - Data Sources
  - Virtual Graphs
- name: Virtual Graphs External Compute
  tags:
  - Virtual Graphs External Compute
- name: Server
  tags:
  - Monitoring
  - Stored Functions
  - Server Status/Metrics
  - Server Admin
  - Queries
  - Cluster Admin
- name: Database
  tags:
  - Checkpoints
  - DB Admin
  - Integrity Constraints / SHACL
  - Data Caching
  - Graph Store Protocol
  - Matcher, aligning schemas from various data sources
  - Reasoning
  - Transactions
  - GraphQL
  - SPARQL
  - EntityResolution
- name: Security
  tags:
  - Roles
  - Permissions
  - Users
- name: Knowledge Catalog
  tags:
  - Knowledge Catalog
