openapi: 3.2.0
info:
  title: Stardog HTTP Knowledge Catalog API
  description: '# Overview

    Stardog supports the standard SPARQL Protocol HTTP bindings, as well as additional functionality via HTTP.'
  contact:
    url: https://stardog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 12.0.3
  x-logo:
    url: https://d33wubrfki0l68.cloudfront.net/66e9dcff51317cfc11b9f3d4ce2917a11ba81681/543c1/img/stardog-logo-optimized.svg
servers:
- url: http://localhost:5820
tags:
- name: Knowledge Catalog
  description: Operations for managing the Knowledge Catalog module
paths:
  /admin/catalog/jobs/cron/is_valid:
    post:
      tags:
      - Knowledge Catalog
      summary: Validates cron string
      description: Checks if the string is a valid Quartz cron schedule. Returns true if valid and false if it is not valid.
      operationId: isValidSchedule
      responses:
        '200':
          description: Validation Result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CATALOG_JOB_CRON_VALID'
  /admin/catalog/credentials/{key}:
    delete:
      tags:
      - Knowledge Catalog
      summary: Remove credentials from catalog
      description: Removes the credentials for the specified key
      operationId: deleteCredentials
      parameters:
      - name: key
        in: path
        description: The credential key
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Credential successfully removed
  /admin/catalog/reload:
    post:
      tags:
      - Knowledge Catalog
      summary: Reloads metadata from a provider
      description: Drops and reloads the metadata for the specified provider
      operationId: reloadCatalog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CATALOG_RELOAD'
        required: true
      responses:
        '204':
          description: Virtual graph imported
  /admin/catalog/reloadModel:
    post:
      tags:
      - Knowledge Catalog
      summary: Drops and reloads the built-in model for the catalog
      operationId: reloadModel
      responses:
        '200':
          description: Model reloaded
  /admin/catalog/jobs/run:
    post:
      tags:
      - Knowledge Catalog
      summary: Runs the specified job
      description: Triggers the scheduled job to run immediately
      operationId: runJob
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CATALOG_JOB'
        required: true
      responses:
        '204':
          description: Job Submitted
  /admin/catalog/credentials:
    get:
      tags:
      - Knowledge Catalog
      summary: Get credentials list
      description: Returns a list of stored credentials
      operationId: getCredentials
      responses:
        '200':
          description: Operation successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CREDENTIALS_LIST'
    post:
      tags:
      - Knowledge Catalog
      summary: Stores username and password data
      description: Stores username and password data and returns an associated access key
      operationId: createAccessKey
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CREDENTIALS_ADD'
        required: true
      responses:
        '201':
          description: Access key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ACCESS_KEY'
  /admin/catalog/jobs/cron/summary:
    post:
      tags:
      - Knowledge Catalog
      summary: Provides a cron summary
      description: Returns a text explanation of the cron string.
      operationId: getScheduleSummary
      responses:
        '200':
          description: Cron Summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CATALOG_JOB_CRON_SUMMARY'
  /admin/catalog/jobs/cron/next_date:
    post:
      tags:
      - Knowledge Catalog
      summary: Returns the next scheduled date
      description: Returns the next date the cron schedule would fire a job.
      operationId: getNextScheduleDate
      responses:
        '200':
          description: Next Date
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CATALOG_JOB_CRON_NEXT_DATE'
  /admin/catalog/status:
    get:
      tags:
      - Knowledge Catalog
      summary: Knowledge Catalog status
      description: Returns status information about the catalog, metadata providers and scheduled jobs
      operationId: getStatus
      responses:
        '200':
          description: Knowledge Catalog status data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CATALOG_STATUS'
components:
  schemas:
    CATALOG_JOB:
      properties:
        jobname:
          type: string
    CATALOG_RELOAD:
      properties:
        provider:
          type: string
          format: URI
    CATALOG_JOB_STATUS:
      properties:
        name:
          type: string
        group:
          type: string
        prev:
          type: string
        next:
          type: string
    ACCESS_KEY:
      properties:
        accessKey:
          type: string
    CATALOG_STATUS:
      properties:
        scheduler:
          type: string
        started:
          type: string
        threads:
          type: integer
          format: int64
          example: 42
        providers:
          type: array
          items:
            $ref: '#/components/schemas/CATALOG_PROVIDER'
        jobs:
          type: array
          items:
            $ref: '#/components/schemas/CATALOG_JOB_STATUS'
    CATALOG_JOB_CRON_VALID:
      properties:
        cron:
          type: string
        is_valid:
          type: boolean
    CATALOG_JOB_CRON_SUMMARY:
      properties:
        cron:
          type: string
        summary:
          type: string
    CREDENTIALS_ADD:
      properties:
        username:
          type: string
        password:
          type: string
        label:
          type: string
    CATALOG_JOB_CRON_NEXT_DATE:
      properties:
        cron:
          type: string
        next_date:
          type: string
    CATALOG_PROVIDER:
      properties:
        name:
          type: string
        type:
          type: string
        schedule:
          type: string
        lastupdate:
          type: string
    CREDENTIALS_LIST:
      properties:
        label:
          type: string
        key:
          type: string
externalDocs:
  url: https://docs.stardog.com
x-tagGroups:
- name: Data Unification
  tags:
  - Data Sources
  - Virtual Graphs
- name: Virtual Graphs External Compute
  tags:
  - Virtual Graphs External Compute
- name: Server
  tags:
  - Monitoring
  - Stored Functions
  - Server Status/Metrics
  - Server Admin
  - Queries
  - Cluster Admin
- name: Database
  tags:
  - Checkpoints
  - DB Admin
  - Integrity Constraints / SHACL
  - Data Caching
  - Graph Store Protocol
  - Matcher, aligning schemas from various data sources
  - Reasoning
  - Transactions
  - GraphQL
  - SPARQL
  - EntityResolution
- name: Security
  tags:
  - Roles
  - Permissions
  - Users
- name: Knowledge Catalog
  tags:
  - Knowledge Catalog
