openapi: 3.2.0
info:
  title: Stardog HTTP Monitoring API
  description: '# Overview

    Stardog supports the standard SPARQL Protocol HTTP bindings, as well as additional functionality via HTTP.'
  contact:
    url: https://stardog.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: 12.0.3
  x-logo:
    url: https://d33wubrfki0l68.cloudfront.net/66e9dcff51317cfc11b9f3d4ce2917a11ba81681/543c1/img/stardog-logo-optimized.svg
servers:
- url: http://localhost:5820
tags:
- name: Monitoring
  description: Operations relating to monitoring processes on the server
paths:
  /admin/processes:
    get:
      tags:
      - Monitoring
      summary: List processes
      description: Get a list of all running processes
      operationId: listProcesses
      parameters:
      - name: all
        in: query
        description: Whether to include all processes in cloud
        schema:
          type: boolean
      responses:
        '200':
          $ref: '#/components/responses/PROCESS_LIST'
  /admin/processes/{name}:
    get:
      tags:
      - Monitoring
      summary: Get process
      description: Get details of a specific process
      operationId: getProcess
      parameters:
      - $ref: '#/components/parameters/name_process'
      responses:
        '200':
          $ref: '#/components/responses/PROCESS'
        '404':
          $ref: '#/components/responses/NAME_PROCESS_404'
    delete:
      tags:
      - Monitoring
      summary: Kill process
      operationId: killProcess
      parameters:
      - $ref: '#/components/parameters/name_process'
      responses:
        '204':
          description: Process killed
        '404':
          $ref: '#/components/responses/NAME_PROCESS_404'
components:
  schemas:
    PROCESS:
      required:
      - type
      - db
      - endTime
      - startTime
      - id
      - user
      - status
      properties:
        type:
          type: string
          example: query
        db:
          type: string
          description: The database on which the query is running
        endTime:
          type: integer
          description: The UNIX timestamp at which the process ended, or -1 if it is still running
          format: int64
        startTime:
          type: integer
          description: The UNIX timestamp when the process started running
          format: int64
        id:
          type: string
        user:
          type: string
          description: The user that initiated the query
        status:
          type: string
          enum:
          - Not started
          - Pre-execution
          - Running
          - Terminating
          - Done
    PROCESS_LIST:
      required:
      - processes
      properties:
        processes:
          type: array
          items:
            $ref: '#/components/schemas/PROCESS'
  responses:
    PROCESS:
      description: Process
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PROCESS'
    PROCESS_LIST:
      description: List of Processes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PROCESS_LIST'
    NAME_PROCESS_404:
      description: Process does not exist
      content:
        application/json:
          schema:
            required:
            - message
            - code
            properties:
              message:
                type: string
                example: Process does not exist
              code:
                type: string
                example: QEQNF2
  parameters:
    name_process:
      name: name
      in: path
      description: The name of the process
      required: true
      schema:
        type: string
externalDocs:
  url: https://docs.stardog.com
x-tagGroups:
- name: Data Unification
  tags:
  - Data Sources
  - Virtual Graphs
- name: Virtual Graphs External Compute
  tags:
  - Virtual Graphs External Compute
- name: Server
  tags:
  - Monitoring
  - Stored Functions
  - Server Status/Metrics
  - Server Admin
  - Queries
  - Cluster Admin
- name: Database
  tags:
  - Checkpoints
  - DB Admin
  - Integrity Constraints / SHACL
  - Data Caching
  - Graph Store Protocol
  - Matcher, aligning schemas from various data sources
  - Reasoning
  - Transactions
  - GraphQL
  - SPARQL
  - EntityResolution
- name: Security
  tags:
  - Roles
  - Permissions
  - Users
- name: Knowledge Catalog
  tags:
  - Knowledge Catalog
